Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using TheBookCave.Data;
using TheBookCave.Models;
using TheBookCave.Models.EntityModels;
using TheBookCave.Models.ViewModels;
using TheBookCave.Models.InputModels;
using TheBookCave.Repositories;

namespace TheBookCave.Controllers
{
    public class BookController : Controller
    {
        private BookRepo _bookRepo;

        public BookController()
        {
            _bookRepo = new BookRepo();
        }

        [HttpGet]
        public IActionResult Index()
        {
            var books = _bookRepo.GetAllBooks();
            return View(books);
        }
        [HttpPost]
        public IActionResult Index(string searchString)
        {

            if (!String.IsNullOrEmpty(searchString))
            {
                var resultBooks = _bookRepo.GetBooksBySearch(searchString);
                return View(resultBooks);
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public IActionResult ListOfBooks(string genre)
        {
            if (genre == null)
            {
                return ListOfBooks();
            }
            else
            {
                var genrelistBooks = _bookRepo.GetBooksByGenre(genre);
                return View(genrelistBooks);
            }

        }
        [HttpGet]
        public IActionResult ListOfBooks()
        {
            var books = _bookRepo.GetAllBooks();
            //return View("ListOfBooks");
            return View(books);
        }

        [HttpPost]
        public IActionResult SortBooks(string sort)
        {
            var sortedBooks = _bookRepo.GetAllBooks();
            if (sort == null)
            {
                return ListOfBooks();
            }
            if (sort == "A to Z")
            {
                sortedBooks = _bookRepo.SortBooksAscending();
            }
            else if (sort == "Z to A")
            {
                sortedBooks = _bookRepo.SortBooksDescending();
            }
            else if (sort == "Lower prices")
            {
                sortedBooks = _bookRepo.SortBooksLowest();
            }
            else if (sort == "Higher prices")
            {
                sortedBooks = _bookRepo.SortBooksHigest();
            }
            return View(sortedBooks);
        }

        [HttpGet]
        public IActionResult BookDetails(string isbn)
        {
            if (isbn == null)
            {
                return View("Error");
            }

            var bookbyISBN = _bookRepo.GetBookByISBN(isbn);

            return View(bookbyISBN);

        }
        
        [Authorize]
        [HttpGet]
        public IActionResult BookReviewRate()
        {

            return View();
        }

        [Authorize]
        [HttpPost] 
        public IActionResult BookReviewRate(BookInputModel book)
        {   
            if(ModelState.IsValid)
            {  
                 SeedData(book);
                 return RedirectToAction("Index");
            }

            return View();

        }
        public static void SeedData(BookInputModel book)
        {   
            var book_db = new DataContext();
            var book_rated = book_db.Books.Select(x => x.Id).FirstOrDefault();
            {   
                new Book()
                {   
                  
                     Rating = book.Rating,
                     Review = book.Review,
            
                };  

            };
       
                book_db.SaveChanges();
                
        }

        public IActionResult NewBooks()
        {
            var newestBooks = _bookRepo.GetNewArrivals();
            return View(newestBooks);
        }

        [HttpGet]
        public IActionResult TopTenBooks()
        {
            var toptenBooks = _bookRepo.GetTop10Books();
            return View(toptenBooks);
        }
        public IActionResult AboutUs()
        {
            return View("AboutUs");
        }
        public IActionResult ContactUs()
        {
            return View("ContactUs");
        }
    }
}

Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using TheBookCave.Repositories;
using TheBookCave.Models.EntityModels;
using TheBookCave.Data;
using TheBookCave.Models.ViewModels;
using TheBookCave.ViewModels;

namespace TheBookCave.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        
        private CartRepo _cartRepo;
        private DataContext _db;

        private BookRepo _bookRepo;

        public CartController()
        {
            _cartRepo = new CartRepo();
            _bookRepo = new BookRepo();
            _db = new DataContext();
        }
        public IActionResult ShoppingCart()
        {
            return View("ShoppingCart");
        }

        public IActionResult AccessDenied()
        {
            return RedirectToAction("LogIn", "User", new { area = "" });
        }

        
        [HttpPost]
        public IActionResult AddToCart(int id)
        {   
            //var cartItem = _cartRepo.GetCart().SingleOrDefault();
            //var cartItem = _db.Cart;
             var cartdb = new DataContext();
             var cartItem = new List<Cart>
             {
                new Cart()
                {
                    BookId = id,
                }


             };
            var selectedBook = (from b in _bookRepo.GetAllBooks()
                                orderby b.Id
                                select b).ToList(); 
       
               
               cartdb.AddRange(cartItem);
               cartdb.SaveChanges();
                return View(selectedBook);            
            
             
            
        }
        [HttpGet]
          public IActionResult Step1()
        {
            return View();
        }
           public IActionResult Step2()
        {
            return View();
        }
            public IActionResult Step3()
        {
            return View();
        }


    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"]</title>
        <environment include="Development">
            <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
            <link rel="stylesheet" href="~/css/site.min.css" />
        </environment>
        <environment exclude="Development">
            <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
                asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
                asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
            <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
            <link rel="stylesheet" href="~/css/footer.css" asp-append-version="true"  />
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
            <link href="https://fonts.googleapis.com/css?family=Cabin+Condensed" rel="stylesheet">
        </environment>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container-fluid topnav">
                <div class="navbar-header">
                    <a class="navbar-brand" asp-controller="Book" asp-action="Index">
                    <img src="~/images/TheBookCaveLogo.jpg" alt="logo.png"></a>
                </div>
                <form class="navbar-form navbar-left searchbar" asp-controller="Book" asp-action="Index" method="POST">
                    <div class="input-group">
                        <input type="text" class="form-control" name="SearchString" placeholder="Looking for a book?">
                        <div class="input-group-btn">
                            <button class="btn btn-default search" type="submit">
                            <i class="glyphicon glyphicon-search"></i>
                            </button>
                        </div>
                    </div>
                </form>
                  <ul class="nav navbar-nav navbar-right">
                     <li><a asp-controller="Cart" asp-action="ShoppingCart"><span style="color:white" class="glyphicon glyphicon-shopping-cart"></span></a></li>
                 </ul>
              @await Html.PartialAsync("_LoginPartial")
            </div>
            <nav class="navbar navbar-inverse bottom">
                <ul class="nav navbar-nav links">
                    <li><a id="list" asp-area="" asp-controller="Book" asp-action="ListOfBooks">Book Catalogue</a></li>
                    <li><a id="top" asp-area="" asp-controller="Book" asp-action="TopTenBooks">Top Ten Books</a></li>
                    <li><a id="new" asp-area="" asp-controller="Book" asp-action="NewBooks">New Arrivals</a></li>
                    <li><a id="about" asp-area="" asp-controller="Book" asp-action="AboutUs">About us</a></li>
                </ul>
            </nav>
        </nav>
        @RenderBody()
        <hr />
        <!--Footer-->
        <footer class="page-footer font-small blue pt-4 mt-4">
            <!--Footer Links-->
            <div class="container-fluid text-center text-md-left">
            <div class="row">
                <!--First column-->
                <div class="col-md-6">
                    <i class="fa fa-envelope"></i> 
                    <span>Lets talk!</span>
                    </br>
                    <a class="contact-us" asp-area="" asp-controller="Book" asp-action="ContactUs">Contact us</a>   
                </div>
                <div class="row">
                    <!--/.Second column-->
                    <div class="col-md-6">
                        <i class="fa fa-users"></i>
                        <span>Who are we?</span>
                        </br>
                        <a class="about-us" asp-area="" asp-controller="Book" asp-action="AboutUs">About us</a>   
                    </div>
                    <div class="social-media">
                        <a href="#" class="fa fa-facebook"></a>
                        <a href="#" class="fa fa-twitter"></a>
                        <a href="#" class="fa fa-instagram"></a>
                    </div>
                    <div class="footer-copyright py-3 text-right">© 2018 The Book Cave</div>
                </div>
            </div>
        </footer>
    </body>
</html>